### ISSUE TITLE
Broken image on command-line lesson 02-filesystem

### ISSUE THREAD

**Issue by MilanGrujicic** [codedex-io/command-line-101#2]
Hello team,

I would like to report an issue in this [page](https://www.codedex.io/command-line/02-filesystem).

The img tag with alt 'Filesystem diagram' is not being displayed correctly. This issue happens on Chrome and Brave.

Please see the attached image for more context. 👇
![Screenshot_2023-10-30_01-27-25](https://github.com/codedex-io/command-line-101/assets/48260426/c4168e72-f487-4cec-9ed1-6a0f8d3c72c8)

**Comment by sonnynomnom** [comment]
Fixed by @Dusch4593!
