### ISSUE TITLE
Two typos in lesson 06. Scavenger Hunt

### ISSUE THREAD

**Issue by MilanGrujicic** [codedex-io/command-line-101#3]
Hello team,

I would like to report two typos/gramatical improvements from this [lesson](https://www.codedex.io/command-line/06-treasure-hunt).

1. Replace 'A brief of history about the command line.' with 'A brief history of the command line'.
![Screenshot_2023-10-30_01-48-05](https://github.com/codedex-io/command-line-101/assets/48260426/f89c749e-796b-422e-9826-92127337ea83)

2. Replace 'just run this command get back to scavenger-hunt' with 'just run this command to get back to scavenger-hunt' 
![Screenshot_2023-10-30_01-42-50](https://github.com/codedex-io/command-line-101/assets/48260426/8dab9a2a-b0cb-47f6-961d-49418b665860)

**Comment by sonnynomnom** [comment]
lololol i think this closed beta course is off the table. but we'll give +2 for the effort. fixed:

https://github.com/codedex-io/curriculum/commit/26c2e58c6265b7bc6b45936c9eda2a39d59512af
